### ISSUE TITLE
Missing install.xml

### ISSUE THREAD

**Issue by michaelherger** [philippe44/LMS-YouTube#1]
There's no install.xml file in git. Is this by purpose? After all it should always have the same UUID etc.

**Comment by philippe44** [comment]
You mean a repository install file ? Yes, that would be on purpose because the packaged installation is on sourceforge. I did that because GitHub only accepts HTTPS for download and some Linux LMS installation do not have SSL. I know this is needed ultimately for YouTube but this is the model I took for plugin on my UPnP plugin as this one does not require SSL to work

**Comment by michaelherger** [comment]
No, the install.xml file needed to be included in the zip-file. Without that file the plugin wouldn't be loaded by LMS. When I tried to run it from a git clone it didn't work until I copied install.xml from the zip file.

**Comment by philippe44** [comment]
Oh then this is a mistake - I probably have a .gitignore that excludes XML files. I'll correct that

**Comment by michaelherger** [comment]
Fixed, thanks!
