### ISSUE TITLE
Youtube plugin error

### ISSUE THREAD

**Issue by tom11as** [philippe44/LMS-YouTube#21]
Hi, since yesterday the LMS Youtube plugin isn't working anymore. The server.log file contains these messages: 
[20-05-06 22:15:48.0510] Plugins::YouTube::WebM::__ANON__ (700) could not get codec info: Cannot request non-HTTP URL 
[20-05-06 22:15:48.0556] Plugins::YouTube::WebM::__ANON__ (640) could not find start offset. 
What is the problem? 
Thanks  Tom

**Comment by philippe44** [comment]
Let's see on the LMS forum

**Comment by KjellVerb** [comment]
I can't find a reference to this issue on the LMS forum but I'm facing the same issue. Did it get solved?

**Comment by pstroug** [comment]
Hi I have the same problem and I get the same response in server log.I opened a case also in slimdevices forum but nobody responses

**Comment by tom11as** [comment]
Hi on my Raspi I did a fresh installation of piCorePlayer v6.0.0 and the Youtube plugin. Then under "Server Settings > Plugins > YouTube" I entered my 3 keys (YouTube API access key, Client ID, Client Secret). After that "Get Code" and "Refresh". Success. I don't know the reason why it stopped working before but the complete reinstallation solved my problem. I hope it works for you also. Tom

**Comment by pstroug** [comment]
Hi Tom,thanks a lot for your response.When you say fresh installation you mean to power down and up the Raspi in order to reload the picoreplayer?Also do I need to enter client id and client secret if I don' t want to use personal account for playlists etc?Thanks again for your help
Regards/Panagiotis

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Σάβ, 30 Μαΐ, 2020 στις 17:56, ο χρήστηςtom11as<notifications@github.com> έγραψε:   


Hi on my Raspi I did a fresh installation of piCorePlayer v6.0.0 and the Youtube plugin. Then under "Server Settings > Plugins > YouTube" I entered my 3 keys (YouTube API access key, Client ID, Client Secret). After that "Get Code" and "Refresh". Success. I don't know the reason why it stopped working before but the complete reinstallation solved my problem. I hope it works for you also. Tom

**Comment by tom11as** [comment]
I mean a fresh installation of the piCorePlayer image on your SD card, not only power down and up. 
To use the plugin I guess you have to enter the Youtube keys. Otherwise probably no connection to Youtube. But I am not an expert for the plugin. That's the way I use it and it works.

**Comment by pstroug** [comment]
Thanks Tom.I"ll try it 
Panagiotis

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Κυρ, 31 Μαΐ, 2020 στις 15:57, ο χρήστηςtom11as<notifications@github.com> έγραψε:   


I mean a fresh installation of the piCorePlayer image on your SD card, not only power down and up.
To use the plugin I guess you have to enter the Youtube keys. Otherwise probably no connection to Youtube. But I am not an expert for the plugin. That's the way I use it and it works.

**Comment by pstroug** [comment]
Hi,I installed the new version of youtube plugin (v0.101.0) and the problem is solved!!
Thanks guys/Panagiotis

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Κυρ, 31 Μαΐ, 2020 στις 15:57, ο χρήστηςtom11as<notifications@github.com> έγραψε:   


I mean a fresh installation of the piCorePlayer image on your SD card, not only power down and up.
To use the plugin I guess you have to enter the Youtube keys. Otherwise probably no connection to Youtube. But I am not an expert for the plugin. That's the way I use it and it works.
